version: 1
disable_existing_loggers: false

formatters:
  access:
    (): "uvicorn.logging.AccessFormatter"
    fmt: '%(levelprefix)s %(asctime)s : %(name)s : %(client_addr)s - "%(request_line)s" %(status_code)s'
    use_colors: true
handlers:
  access:
    formatter: access
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
  file:
    formatter: access
    class: logging.FileHandler
    level: DEBUG
    filename: "./app.log"
loggers:
  uvicorn.access:
    handlers: [access, file]
    level: DEBUG
    propagate: no
root:
  handlers: [access]
  level: INFO
  propagate: no

